/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as MinhaAgendaRouteImport } from './routes/minha-agenda'
import { Route as EscalasNovaRouteImport } from './routes/escalas.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAgendaRoute = MinhaAgendaRouteImport.update({
  id: '/minha-agenda',
  path: '/minha-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasNovaRoute = EscalasNovaRouteImport.update({
  id: '/escalas/nova',
  path: '/escalas/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/minha-agenda': typeof MinhaAgendaRoute
  '/escalas/nova': typeof EscalasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/minha-agenda': typeof MinhaAgendaRoute
  '/escalas/nova': typeof EscalasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/minha-agenda': typeof MinhaAgendaRoute
  '/escalas/nova': typeof EscalasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipe' | '/minha-agenda' | '/escalas/nova'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipe' | '/minha-agenda' | '/escalas/nova'
  id: '__root__' | '/' | '/equipe' | '/minha-agenda' | '/escalas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipeRoute: typeof EquipeRoute
  MinhaAgendaRoute: typeof MinhaAgendaRoute
  EscalasNovaRoute: typeof EscalasNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-agenda': {
      id: '/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/minha-agenda'
      preLoaderRoute: typeof MinhaAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas/nova': {
      id: '/escalas/nova'
      path: '/escalas/nova'
      fullPath: '/escalas/nova'
      preLoaderRoute: typeof EscalasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipeRoute: EquipeRoute,
  MinhaAgendaRoute: MinhaAgendaRoute,
  EscalasNovaRoute: EscalasNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
